### ISSUE TITLE
[22.4.1] Source code signature is missing

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsad#111]
For the tar ball of the source code, the signature is missing.
![Screenshot 2023-01-09 at 13-44-00 Release gsad 22 4 1 · greenbone_gsad](https://user-images.githubusercontent.com/837503/211310872-8ebb4f80-bf2b-43f7-8103-4dd803865985.png)

**Comment by bjoernricks** [comment]
Just uploaded the signatures. The CI was not set up correctly.
