### ISSUE TITLE
Cmake  Error

### ISSUE THREAD

**Issue by meetgyn** [greenbone/gsad#42]
![image](https://user-images.githubusercontent.com/3695608/146423272-cb2433da-495b-4384-8554-2d331c9d797d.png)

![image](https://user-images.githubusercontent.com/3695608/146423185-e6a9a7a4-7448-4bfc-bbe9-278d55b356d1.png)

**Comment by y0urself** [comment]
Please use and fill our [ISSUE TEMPLATE](https://github.com/greenbone/gsad/tree/main/.github/ISSUE_TEMPLATE). We won't provide help from a screenshot.
