### ISSUE TITLE
GVM start failed due to "greenbone-security-assistant" will be removed in "apt install gvm" procedure on Raspberry Pi 2

### ISSUE THREAD

**Issue by josh-otwise** [greenbone/gsad#52]
### Expected behavior
GVM start succeed.
* GIVEN I start GVM (``sudo gvm-start``)
* WHEN I installed GVM (``sudo apt install gvm``)
* THEN GVM started, and web UI opened automatically

### Actual behavior
GVM start failed.
* GIVEN I start GVM (``sudo gvm-start``)
* WHEN I installed GVM (``sudo apt install gvm``)
* THEN GVM start failed
* THEN I got an error message: ``Failed to start greenbone-security-assistant.service: Unit greenbone-security-assistant.service is masked.``

### Root cause (?)
A required package / service ``greenbone-security-assistant`` (the "assistant") has been removed in "apt install gvm" procedure.

And I can not install "assistant" to fix this problem manually, because another "dependency issue" as the following.

 ```shell
libgvm20 : Conflicts: libopenvas9 but 9.0.3-1.1 is to be installed
```

### Steps to reproduce
1. Let your Raspberry Pi 2 with Pi OS ready
2. Install GVM by APT: ``sudo apt install gvm``
3. Start GVM: ``sudo gvm-start``

### GVM versions
**gvm: 20.08.0** (gvmd --version)

### Environment
* h/w: Raspberry Pi 2, Model B
* s/w -- [Raspberry Pi OS with desktop
](https://www.raspberrypi.com/software/operating-systems/)
  * Release date: January 28th 2022
  * System: 32-bit
  * Kernel version: 5.10
  * Debian version: 11 (bullseye)

**Comment by bjoernricks** [comment]
Hi, I am sorry but this is clearly a packaging issue and we can't do anything about that. You need to raise a bug report at the downstream issue tracker (i suppose you are using raspbian so you may take a look at http://www.raspbian.org/RaspbianBugs).
