### ISSUE TITLE
Error em sock

### ISSUE THREAD

**Issue by meetgyn** [greenbone/gsad#57]
### Steps to reproduce
It was working perfectly, but now it is returning this error and I can't identify. When trying to run Scan on some target, he simply to.
### GVM versions

**gsa:** Greenbone Security Assistant 21.4.4

**gvm:** Greenbone Vulnerability Manager 21.4.5

**openvas-scanner:** (openvassd --version)

**gvm-libs:**

### Environment

**Operating system:** Ubuntu 20.4

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"

**Installation method / source:** (packages, source installation)
Source installation with link  https://www.libellux.com/openvas/#enable-and-start-services

### Logfiles
md manage:WARNING:2022-05-13 13h20.17 UTC:5090: osp_scanner_feed_version: failed to connect to /run/ospd/ospd-openvas.sock
md manage:WARNING:2022-05-13 13h20.28 UTC:5050: Could not connect to Scanner at /run/ospd/ospd-openvas.sock

```
```

**Comment by bjoernricks** [comment]
Hi, you need to ensure that ospd-openvas is running and listens at `/run/ospd/ospd-openvas.sock`. This is **not** an issue with gsad.
