### ISSUE TITLE
How to close GSAD's HTTPonly ? 

### ISSUE THREAD

**Issue by UsoulKind** [greenbone/gsad#87]
--http-only                            Serve HTTP only, without SSL.
--------------------------------------------------------------------------
Can I use ‘--http-only’ to control gsad's httponly config? Or , is there any way to close httponly?  I want to get the cookie by script,
Thanks!

![image](https://user-images.githubusercontent.com/68585598/192974709-7f31a4e6-3535-42df-ae4f-5d8c3a0d92a1.png)

**Comment by bjoernricks** [comment]
First of all this is a question and not a bug report. Therefore it would have been raised at https://forum.greenbone.net/ at best.

Second no you can't. And it's by intention. You have two tokens. First the session cookie and second the login token. Only the login token is accessible via JS. The session cookie is set by your browser automatically with every request after a successful login. Thus you don't have to care about it. The login token must be gathered during the login procedure and added to every request.
